// apps/next-website-app-dir/lib/components/pageComponents/bookPageComponents/components/bookListFooter.tsx
import { LinkButton } from "ui/react";

interface Props {
	numBooks: number;
	totalNumBooks: number;
}

/**
 * The footer part of the book list
 * This handles showing the number of books and a button to load more books
 * @param param0
 * @returns
 */
export default function BookListFooter({ numBooks, totalNumBooks }: Props) {
	const nextSetOfBooks = Math.min(numBooks + 10, totalNumBooks);

	return (
		<div className="mt-10 flex flex-col items-center gap-2">
			<p className="m-0 text-sm">
				Showing {numBooks} of {totalNumBooks} books
			</p>
			<LinkButton href={`/books?numBooks=${nextSetOfBooks}`} scroll={false}>
				See more books
			</LinkButton>
		</div>
	);
}

// apps/web-sveltekit/src/lib/components/pageComponents/bookPageComponents/components/bookListFooter.svelte
<script lang="ts">
	import { LinkButton } from "ui/svelte";

	// props
	export let numBooks: number;
	export let totalNumBooks: number;

	$: nextSetOfBooks = Math.min(numBooks + 10, totalNumBooks);
</script>

<div class="mt-10 flex flex-col items-center gap-2">
	<p class="m-0 text-sm">
		Showing {numBooks} of {totalNumBooks} books
	</p>
	<LinkButton href={`/books?numBooks=${nextSetOfBooks}`} noScroll={true}>See more books</LinkButton>
</div>
